#spring:
#    datasource:
#        name: david_demo
##        type: com.alibaba.druid.pool.DruidDataSource
#        #driver-class-name: com.mysql.jdbc.Driver
#         #基本属性
#        #druid相关配置
#        druid:
#          #监控统计拦截的filters
#          filters: stat
#          driver-class-name: com.mysql.jdbc.Driver
#          #基本属性
#          url: jdbc:mysql://47.104.81.41/david_demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#          username: root
#          password: Zj12Zj12
#          #配置初始化大小/最小/最大
#          initial-size: 1
#          min-idle: 1
#          max-active: 20
#          #获取连接等待超时时间
#          max-wait: 60000
#          #间隔多久进行一次检测，检测需要关闭的空闲连接
#          time-between-eviction-runs-millis: 60000
#          #一个连接在池中最小生存的时间
#          min-evictable-idle-time-millis: 300000
#          validation-query: SELECT 'x'
#          test-while-idle: true
#          test-on-borrow: false
#          test-on-return: false
#          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#          pool-prepared-statements: false
#          max-pool-prepared-statement-per-connection-size: 20
#          web-stat-filter:
#            enabled: false

spring:
    datasource:
        url: jdbc:mysql://47.104.81.41/david_demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: Zj12Zj12


    # 静态页面视图解析
#    mvc:
#      view:
#        prefix: /
#        suffix: .html

    # mq配置
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.david.daviddemo.model  # 注意：对应实体类的路径
  sqlsessionFactory: dsf
#  configuration:
#    cache-enabled: true

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

example:
  service:
    enabled:false



